### ISSUE TITLE
如果文档有嵌套对象，序列化时会出现空指针异常

### ISSUE THREAD

**Issue by 96loveslife** [dromara/easy-es#11]
版本：0.9.8
异常场景：新增数据
异常原因：com.xpc.easyes.core.toolkit.EntityInfoHelper#addNameFilter。获取类下所有属性时，不包含子对象的属性。导致从mappingColumnMap中获取映射字段会出现空指针异常。
<img width="701" alt="image" src="https://user-images.githubusercontent.com/28110502/163084935-56537a80-09f6-453d-b8dc-5293ee9bf1b0.png">
测试代码：
<img width="842" alt="image" src="https://user-images.githubusercontent.com/28110502/163085724-99298a74-692f-4e02-a3d1-911af2e29ddd.png">

**Comment by xpc1024** [comment]
嵌套类型及父子类型目前尚未支持,如需此功能可以通过拆宽表方式或我提供的混合查询/原生查询方式完成.
该类型支持预计在未来3个迭代内.

**Comment by 96loveslife** [comment]
0.9.8版本新增的自定义字段映射功能，在新增父子对象时会出现空指针异常。

**Comment by 96loveslife** [comment]
> 嵌套类型及父子类型目前尚未支持,如需此功能可以通过拆宽表方式或我提供的混合查询/原生查询方式完成. 该类型支持预计在未来3个迭代内.


0.9.8版本新增的自定义字段映射功能，在新增父子对象时会出现空指针异常。

**Comment by xpc1024** [comment]
0.9.8版本还不支持父子类型及嵌套类型  至少要到0.9.11版本支持

**Comment by 96loveslife** [comment]
大佬nb，期待新版本！v.v
