### ISSUE TITLE
大小写不敏感

### ISSUE THREAD

**Issue by NiceMoon** [dromara/easy-es#12]
查询时，会自动把字段大写首字母转成小写。。

**Comment by xpc1024** [comment]
目前支持下划线自动转驼峰,以及自定义字段名称功能.
在java中,字段命名是首字母小写的驼峰,我不理解为啥会有字段首字母大写? 您是指在es中该字段的首字母大写吗? 如果是这种情况,您可以在java实体类中对该字段加上@TableField(value="es中该字段的名称")注解,即可解决.

**Comment by NiceMoon** [comment]
对，因为es中的数据是.NET写入的，大驼峰首字母大写。。我在TableFiled中指定了，但没生效。。
![image](https://user-images.githubusercontent.com/22215540/163749307-35ebdc90-3322-422b-b49d-f5d4252c1a7a.png)
![image](https://user-images.githubusercontent.com/22215540/163749323-e95b7db5-6a1d-4272-990b-cb725b1b981f.png)

**Comment by xpc1024** [comment]
无法复现您的问题,需要您这边确认下 注解是否用错了 比如@TableField是否用成了Mybatis-Plus提供的.
正确姿势应该是EE提供的.
![image](https://user-images.githubusercontent.com/38153520/163911347-e350282e-c383-4a69-bc1b-c88cc5329d26.png)
![image](https://user-images.githubusercontent.com/38153520/163911435-e1376513-d532-41bf-9cde-588046218961.png)
![image](https://user-images.githubusercontent.com/38153520/163911466-613d8138-e9a7-4a1f-b68f-d00ce9cd5b76.png)
如果确认无误仍有问题,可尝试升级ee版本至0.9.10,然后配置索引托管模式为手动模式,重新尝试看看能否复现?确定可以复现的话,不妨加答疑群,把您代码提供一下,我们安排人帮免费您解决.
