### ISSUE TITLE
发现缺少不分词查询

### ISSUE THREAD

**Issue by NiceMoon** [dromara/easy-es#13]
发现缺少不分词查询接口

**Comment by xpc1024** [comment]
分不分词取决于字段的索引类型是否为text,是否指定分词器等.
并不缺少不分词查询接口,像eq就是精确匹配,并不分词.但一个字段无法同时既支持分词查询,又支持不分词查询,es本身就不支持.
如果你非要这么做,可以建立该字段的冗余字段,值用同一个,类型一个采用keyword,一个用text,就可以化解.

**Comment by NiceMoon** [comment]
明白了，多谢

**Comment by NiceMoon** [comment]
这是来自兰州大学-信息学院-马月宾的自动回复邮件。您好，我已经收到您的邮件，我会在最短的时间内回复您，谢谢~
