### ISSUE TITLE
org.elasticsearch.common.xcontent.XContentType

### ISSUE THREAD

**Issue by loulangogogo** [dromara/easy-es#133]
Elasticsearch 从 7.16.0 把 `org.elasticsearch.common.xcontent.XContentType` 改为了 `org.elasticsearch.xcontent.XContentType`。目前 ES 7系列的版本已经发展到 7.17.24 ，easy-es官方是否可以升级一下版本。总是使用这个不对应的版本心里有点不对劲。
或者官方给出一个可以手动配置的方式，这样就能兼容高低版本了。

**Comment by lin-youming** [comment]
同求

**Comment by lin-youming** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
