### ISSUE TITLE
Sometimes the connection reset by peer

### ISSUE THREAD

**Issue by NiceMoon** [dromara/easy-es#14]
i use the es-easy, but sometimes the connection reset by peer, why is the problem? the connection keepAlive configuration?
![image](https://user-images.githubusercontent.com/22215540/165007852-9c2dd1a5-147b-40e7-a2e6-7666cf669a18.png)

**Comment by NiceMoon** [comment]
i use the default easy-es configuration.

**Comment by xpc1024** [comment]
you can add the  config below to your springboot application.properties or application.yml

easy-es.connect-timeout=7200 # unit second .  This means the connection will be closed after 7200s, if  there is no request within 2 hours in your project.  you can also increase this value depend on your context.

**Comment by xpc1024** [comment]
A little curious where you come from guys?

**Comment by NiceMoon** [comment]
china

**Comment by xpc1024** [comment]
中国人你不跟我讲汉语... issue确认解决了的麻烦都关闭下  你我发现提了很多issue,但实际上并不是问题,解决了的麻烦帮忙点下关闭,谢了!

**Comment by NiceMoon** [comment]
ok
