### ISSUE TITLE
如果长时间不操作，再操作后会报connection reset by peer

### ISSUE THREAD

**Issue by NiceMoon** [dromara/easy-es#17]
k8s容器部署下，如果长时间不操作，再操作后会报connection reset by peer，怀疑是网关把长时间没有操作的连接给断了。
而且配置connectTimeout并不会解决这个问题，是不是因为keepalive导致的？
![image](https://user-images.githubusercontent.com/22215540/170634969-5b90a1c1-7579-4faa-838b-2c89e5448864.png)

**Comment by xpc1024** [comment]
connection reset by pear 大部分是因为keepalive导致的,我在配置文件中已经提供了配置心跳,你可以配置下心跳keep-alive-millis,单位是毫秒.配置文件可参考官网,比较简单.

**Comment by NiceMoon** [comment]
这是来自兰州大学-信息学院-马月宾的自动回复邮件。您好，我已经收到您的邮件，我会在最短的时间内回复您，谢谢~

**Comment by NiceMoon** [comment]
好的，多谢

**Comment by NiceMoon** [comment]
但我看源码里是
![image](https://user-images.githubusercontent.com/22215540/170641871-f6d12046-a620-48f6-8aea-32ec1874008c.png)

**Comment by NiceMoon** [comment]
但我看源码里是没有这个配置呢？0.9.13版本
![image](https://user-images.githubusercontent.com/22215540/170641997-6a9b3165-116a-4bf3-bc1a-ad1ef2f83485.png)

**Comment by xpc1024** [comment]
升级版本至0.9.16

**Comment by xpc1024** [comment]
升级版本至0.9.16

**Comment by NiceMoon** [comment]
嗯，最新版里看到了，多谢
