### ISSUE TITLE
新版本PageInfo，total返回的是0

### ISSUE THREAD

**Issue by NiceMoon** [dromara/easy-es#18]
新版本PageInfo，total返回的是0
![image](https://user-images.githubusercontent.com/22215540/170943861-b5abfe81-0526-4ee4-b979-0224d8cf84e4.png)

**Comment by xpc1024** [comment]
0.9.20 配置trackTotalHits=true

**Comment by NiceMoon** [comment]
升级到0.9.20版本后，trackTotalHits是默认开启的？

**Comment by xpc1024** [comment]
是的 可以看版本tag
