### ISSUE TITLE
注解标记高亮，导致空指针异常

### ISSUE THREAD

**Issue by jojocodeX** [dromara/easy-es#28]
在insert保存的时候，由于当前需要存储的字段被标记为高亮，在insert时，被标记为高亮字段所在列被忽略，导致序列化过程中出现空指异常。为什么需要插入的时候需要把高亮字段忽略，没太明白作者的意图，我理解不应该忽略该内容，如果需要忽略也是按照具体序列化方式，或者把序列化方式的操作抽象为接口，可以让使用者自己选择

**Comment by xpc1024** [comment]
已解决,升级v1.0.0
