### ISSUE TITLE
读取索引不同

### ISSUE THREAD

**Issue by chimu7** [dromara/easy-es#29]
两台服务，同一个项目，读取的 索引 不一样

**Comment by chimu7** [comment]
其中一台查询报错。索引名为：goodsdetail_s0。   报错信息：{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [goodsdetail_s1]","resource.type":"index_or_alias","resource.id":"goodsdetail_s1","index_uuid":"_na_","index":"goodsdetail_s1"}],"type":"index_not_found_exception","reason":"no such index [goodsdetail_s1]","resource.type":"index_or_alias","resource.id":"goodsdetail_s1","index_uuid":"_na_","index":"goodsdetail_s1"},"status":404}

**Comment by xpc1024** [comment]
索引平滑迁移采用的是最终一致性解决方案,可参考官网文档,调大配置文件中的socketTime值,否则主机器可能会出现失败.
