### ISSUE TITLE
ES官方最新版已经做了对sql的兼容

### ISSUE THREAD

**Issue by kequeen** [dromara/easy-es#30]
读最新的文档，发现官方也已经支持类似的功能了
https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-getting-started.html
`POST /_sql?format=txt
{
  "query": "SELECT * FROM library WHERE release_date < '2000-01-01'"
}`

**Comment by xpc1024** [comment]
官方早就支持SQL了,但功能比较有限和简单,而且就算做到全支持,ORM框架依旧有必要,可类比Mybatis-plus
