### ISSUE TITLE
测试用例报错，缺少springboot-test相关

### ISSUE THREAD

**Issue by zBo1997** [dromara/easy-es#31]
![image](https://user-images.githubusercontent.com/53822786/191426896-2554cfef-97d4-4610-9c5b-6544e00fde1c.png)

**Comment by zBo1997** [comment]
项目是否需要开发人员手动添加相关坐标？

**Comment by xpc1024** [comment]
测试用例均在此目录下https://github.com/dromara/easy-es/tree/main/easy-es-test/src/test/java/cn/easyes/test/all

**Comment by zBo1997** [comment]
示例项目是？？？

**Comment by zBo1997** [comment]
直接删除test
