### ISSUE TITLE
完全按照官方文档写的，但是SpringBoot3.0.3启动报错

### ISSUE THREAD

**Issue by Meta39** [dromara/easy-es#57]
![image](https://user-images.githubusercontent.com/57950116/221803059-fe1df2de-334b-4865-b589-7e4315702571.png)
SpringBoot版本：3.0.3
Elasticsearch版本：7.14.0
依赖引入如下：
`<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.0.3</version>
        <relativePath/> 
    </parent>
    <groupId>com.aoxqwl</groupId>
    <artifactId>eedemo</artifactId>
    <version>1</version>
    <name>eedemo</name>
    <description>eedemo</description>
    <properties>
        <java.version>17</java.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
        
        <dependency>
            <groupId>cn.easy-es</groupId>
            <artifactId>easy-es-boot-starter</artifactId>
            <version>1.1.1</version>
            <exclusions>
                <exclusion>
                    <groupId>org.projectlombok</groupId>
                    <artifactId>lombok</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.elasticsearch.client</groupId>
                    <artifactId>elasticsearch-rest-high-level-client</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.elasticsearch</groupId>
                    <artifactId>elasticsearch</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.elasticsearch.client</groupId>
            <artifactId>elasticsearch-rest-high-level-client</artifactId>
            <version>7.14.0</version>
        </dependency>
        <dependency>
            <groupId>org.elasticsearch</groupId>
            <artifactId>elasticsearch</artifactId>
            <version>7.14.0</version>
        </dependency>
    </dependencies>`

**Comment by Meta39** [comment]
![image](https://user-images.githubusercontent.com/57950116/221803880-2dce97e2-0ff4-43ac-ba90-9088957109c4.png)
上面可能不太好看，截图了。

**Comment by xpc1024** [comment]
3.x spirngboot暂不支持
