### ISSUE TITLE
SpringBoot 3.0.4 无法正常使用

### ISSUE THREAD

**Issue by angleGhost** [dromara/easy-es#59]
plugins {
    id 'java'
    id 'org.springframework.boot' version '3.0.4'
    id 'io.spring.dependency-management' version '1.1.0'
   }
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation('org.springframework.boot:spring-boot-starter-web') {
        exclude(group: 'org.elasticsearch.client', module: 'elasticsearch-rest-high-level-client')
        exclude(group: 'org.elasticsearch', module: 'elasticsearch')
    }
    implementation('org.springframework.boot:spring-boot-starter-webflux') {
        exclude(group: 'org.elasticsearch.client', module: 'elasticsearch-rest-high-level-client')
        exclude(group: 'org.elasticsearch', module: 'elasticsearch')
    }
    implementation 'io.github.xpc1024:easy-es-boot-starter:Latest Version'
    implementation 'org.elasticsearch.client:elasticsearch-rest-high-level-client:7.14.0'
    implementation 'org.elasticsearch:elasticsearch:7.14.0'
    
    以上是导包信息，启动还是会报错：
    Description:
    Field client in cn.easyes.starter.register.MapperFactoryBean required a bean of type 'org.elasticsearch.client.RestHighLevelClient' that could not be found.
    
    group：cn.easy-es的包也已经尝试，都一样

**Comment by jianhao2010303** [comment]
3.0.5 启动报错 Field client in cn.easyes.starter.register.MapperFactoryBean required a bean of type 'org.elasticsearch.client.RestHighLevelClient' that could not be found.
