### ISSUE TITLE
有没有JAVA语言无框架依赖版本

### ISSUE THREAD

**Issue by janyyy** [dromara/easy-es#7]
有没有JAVA语言无框架依赖版本，基于JAVA语言。我看目前该框架依赖于SpringBoot

**Comment by xpc1024** [comment]
没有哦,之所以依赖sprint-autoconfigration也是为了方便用户使用,毕竟springboot已经是主流了

**Comment by J-Orange** [comment]
如果哪天支持了非springboot项目 记得@我
