### ISSUE TITLE
Add ability to configure TLS certificate and set ApiCompatibilityMode to support ElasticSearch 8

### ISSUE THREAD

**Issue by linghengqian** [dromara/easy-es#9]
- In `ElasticSearch` 8.x, `TLS` and user authentication are enabled by default, can the developer suggest how to set `http_ca.crt` at https://github.com/xpc1024/easy-es-springboot-demo ? 

- Here are two blog posts about how to connect via `TLS` certificate under `co.elastic.clients:elasticsearch-java:8.1.1`, but it would be better if some friends can give the introduction of global configuration of TLS certificate in `easy-es` (Maybe in `application.yml`). Refer to https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/8.1/_encrypted_communication.html and https://spinscale.de/posts/2022-02-17-running-elasticsearch-8-with-testcontainers.html .

- I noticed that the component is using `RestHighLevelClient`, which means that if somebody need to connect to the `ElasticSearch` 8.x cluster, he need to add the environment variable `ELASTIC_CLIENT_APIVERSIONING: true` for `ElasticSearch`. For this part, please refer to https://www.elastic.co/guide/en/elasticsearch/reference/current/rest-api-compatibility.html .  Hope that helps with the corresponding tests.

- As a supplement, developers should try adding a property set to HLRC's `client.setApiCompatibilityMode(true)` in the `easy-es` configuration class. See https://github.com/elastic/elasticsearch/issues/77859, which helps in finding issues with unit tests in Elastic Stack 8.x versions without setting client-side environment variables.

- Also, there is a clarification as https://discuss.elastic.co/t/migration-from-hlrc-to-java-api/300479 , `HLRC version 7.17.1` and `Java API client 8.x`, both use the same `RestClient` for http communication, and they can coexist in the same project, I think it can be gradually migrated to the new client on `easy-es`. Of course, the `Java API client 8.x` is basically generated by the API specification, This leads to the fact that although its API is stable, its documentation is still not finished, and somebody need to go to `JavaDoc` to see more information.

**Comment by xpc1024** [comment]
抱歉,8.x版本我们目前暂不支持 未来8.x版本用的人多了我们会考虑支持
