### ISSUE TITLE
希望支持租户切换, 并且加入类似mp的MetaObjectHandler这样的公共字段处理配置

### ISSUE THREAD

**Issue by krisklee** [dromara/easy-es#97]
1. 因为有租户切换需求, 目前想在索引上做区分, 但是好像不好实现, 现在只能在每个条件里加入条件判断
2. 希望可以加入类似mp的MetaObjectHandler这样的公共字段处理配置, 可以自定义填充一些字段, 可以的话, 第一点就可以解决了呢

**Comment by Liu3334** [comment]
求代码
